// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface CloudflareEnv {
    CARS_KV: KVNamespace;
    NEXTJS_ENV: string;
    ASSETS: Fetcher;
}
